-- Create table
create table VENDAS
(
  id               NUMBER(9) not null,
  data_hora        DATE not null,
  empresa          NUMBER(9) not null,
  pdv              NUMBER(4) not null,
  nf               NUMBER(9) not null,
  tipo_venda       NUMBER(3),
  operador         NUMBER(6) not null,
  valor            NUMBER(10,2) not null,
  data_hora_inicio DATE not null,
  cnpj_cpf         VARCHAR2(14),
  fator            NUMBER(5,4),
  lancamento       NUMBER(1),
  data_proc        DATE,
  documento        NUMBER(9),
  ecf              NUMBER(6),
  cancelado        CHAR(1),
  id_cliente       NUMBER(9),
  modelo           VARCHAR2(2),
  chave            VARCHAR2(44),
  cpf_nfp          VARCHAR2(14),
  protocolo        VARCHAR2(15),
  entrega          VARCHAR2(1),
  vl_frete         NUMBER(15,2),
  vl_outras_desp   NUMBER(15,2),
  caixas_entrega   VARCHAR2(100),
  nr_sat           NUMBER(9),
  devolucao        VARCHAR2(1) default 'F',
  id_coi           NUMBER(9),
  nao_estornar     VARCHAR2(1)
)

-- Create table
create table VENDAS_DIARIAS
(
  produto                   NUMBER(9) not null,
  empresa                   NUMBER(9) not null,
  data                      DATE not null,
  qtde                      NUMBER(15,4) not null,
  valor                     NUMBER(15,4) not null,
  custo                     NUMBER(15,4),
  margem_lucro              NUMBER(15,4),
  pmz                       NUMBER(15,4),
  impostos                  NUMBER(15,4),
  sugestao                  NUMBER(15,4),
  devolucao                 CHAR(1) not null,
  datahora                  DATE,
  tipovenda                 NUMBER(3) not null,
  customedio                NUMBER(15,4),
  valor_acrescimos_venda    NUMBER(15,4),
  valor_descontos_venda     NUMBER(15,4),
  valor_acordos_venda       NUMBER(15,4),
  valor_icms_venda          NUMBER(15,4),
  valor_pis_venda           NUMBER(15,4),
  valor_cofins_venda        NUMBER(15,4),
  valor_despesas_venda      NUMBER(15,4),
  valor_comissao_venda      NUMBER(15,4),
  data_proc                 DATE,
  valor_embalagem           NUMBER(15,4),
  valor_impostos_debitaveis NUMBER(15,4),
  valor_margem_lucro        NUMBER(15,4),
  id_area_vendas            NUMBER(9),
  qtde_promocao             NUMBER(15,3),
  valor_acordos_pack        NUMBER(15,4),
  vl_icms_st_a              NUMBER(15,2),
  vl_ipi_a                  NUMBER(15,2),
  em_oferta                 VARCHAR2(1),
  qtde_cancelamento         NUMBER(15,4)
)

-- Create table
create table ITENS_VENDA
(
  venda                     NUMBER(9) not null,
  produto                   NUMBER(9) not null,
  qtde                      NUMBER(9,3) not null,
  valor                     NUMBER(10,2) not null,
  desconto                  NUMBER(10,2) not null,
  vendedor                  NUMBER(9),
  id                        NUMBER(10) not null,
  custoicms                 NUMBER(10,4),
  custosicms                NUMBER(10,4),
  vendatab                  NUMBER(10,2),
  cst                       VARCHAR2(3),
  aliquota                  NUMBER(4,2),
  desp_op                   NUMBER(6,4),
  pis                       NUMBER(6,4),
  cofins                    NUMBER(6,4),
  cst_pis                   VARCHAR2(2),
  valor_pis                 NUMBER(10,4),
  cst_cofins                VARCHAR2(2),
  valor_cofins              NUMBER(10,4),
  custo_medio               NUMBER(10,4),
  custo_liquido_medio       NUMBER(10,4),
  acrescimo                 NUMBER(10,2),
  qtde_promocao             NUMBER(9,3),
  cod_promocao              NUMBER(9),
  valor_promocao            NUMBER(12,3),
  tipo_venda                NUMBER(3),
  valor_acordos_venda       NUMBER(15,4),
  valor_icms_venda          NUMBER(15,4),
  valor_despesas_venda      NUMBER(15,4),
  valor_comissao_venda      NUMBER(15,4),
  fator                     NUMBER(5,4),
  valor_embalagem           NUMBER(12,4),
  valor_impostos_debitaveis NUMBER(12,4),
  valor_margem_lucro        NUMBER(15,4),
  id_area_vendas            NUMBER(9),
  vl_icms_st_a              NUMBER(15,2),
  vl_ipi_a                  NUMBER(15,2),
  em_oferta                 VARCHAR2(1),
  ean                       VARCHAR2(16),
  codigo_benef_fiscal       NUMBER(9),
  pontos                    NUMBER(8,4),
  aliq_fcp                  NUMBER(4,2),
  valor_aliq_fcp            NUMBER(15,4),
  cfop                      NUMBER(4),
  desc_motivo_desconto      VARCHAR2(100),
  liberador_desconto        NUMBER(6)
)

-- Create table
create table PRODUTOS
(
  id                     NUMBER(9) not null,
  descritivo             VARCHAR2(128) not null,
  datahora_cadastro      DATE default SYSDATE,
  datahora_alteracao     DATE,
  descritivo_pdv         VARCHAR2(30) not null,
  depto                  NUMBER(2) not null,
  secao                  NUMBER(3) not null,
  grupo                  NUMBER(3) not null,
  subgrupo               NUMBER(3) not null,
  familia                NUMBER(5),
  nutricional            NUMBER(9),
  associado              NUMBER(9),
  unidade_compra         CHAR(2) not null,
  unidade_venda          CHAR(2) not null,
  status                 NUMBER(2) not null,
  composto               NUMBER(2) not null,
  validade               NUMBER(5),
  tp_validade            NUMBER(1),
  receita                VARCHAR2(4000),
  classificacao_fiscal   VARCHAR2(10),
  ipi_tipo               CHAR(1) not null,
  ipi                    NUMBER(4,2) not null,
  qtde_embalagems        NUMBER(8,3) not null,
  qtde_embalageme        NUMBER(8,3) not null,
  piscofins              CHAR(1) not null,
  ipv                    NUMBER(1) not null,
  pesquisa               CHAR(1) not null,
  aceitapdvm             CHAR(1) not null,
  aceitapdve             CHAR(1) not null,
  diasestoque            NUMBER(3) default 0 not null,
  pesol                  NUMBER(9,3) not null,
  pesob                  NUMBER(9,3) not null,
  similar                NUMBER(4),
  sazonal                NUMBER(4),
  cestoque               CHAR(1) not null,
  del_depto              NUMBER(3),
  del_secao              NUMBER(3),
  cor                    VARCHAR2(20),
  pantone                VARCHAR2(20),
  mprima                 NUMBER(4),
  descritivodel          VARCHAR2(100),
  pontos_fidelidade      NUMBER(8,4) default 0 not null,
  base_fidelidade        CHAR(1),
  somentecd              CHAR(1) default 'F' not null,
  despesa                NUMBER(6,4) not null,
  monofasico             VARCHAR2(1) default 'I' not null,
  emite_etiqueta_pedidov CHAR(1) default 'F' not null,
  id_marca_produto       NUMBER(9),
  utiliza_serie          VARCHAR2(1) default 'F' not null,
  origem                 NUMBER(1),
  excecao_icms           VARCHAR2(2),
  lote_venda             NUMBER(6) default 0 not null,
  acrescimo_fracionado   NUMBER(6,2) default 0 not null,
  desconto_maximo        NUMBER(6,2) default 0 not null,
  aceita_troca           VARCHAR2(1) default 'F' not null,
  margem_contribuicao    NUMBER(12,2) default 0 not null,
  licenca                NUMBER(9),
  destinado_maiores      CHAR(1) default 'F' not null,
  alto_risco             CHAR(1) default 'F' not null,
  modo_preparo           VARCHAR2(3000),
  excecao_ipi            VARCHAR2(3),
  unidade_kgl            CHAR(2),
  qtde_kgl               NUMBER(8,3) default 0 not null,
  cest                   VARCHAR2(7),
  conservacao            VARCHAR2(1000),
  antecipacao_arroz      NUMBER(12,4),
  beneficio_isencao      CHAR(1) default 'F',
  utiliza_aliq_interna   CHAR(1) default 'F',
  lastro                 NUMBER(3),
  camada                 NUMBER(3),
  peso_medio             NUMBER(9,3),
  min_dias_validade      NUMBER(5),
  participa_cotacao      CHAR(1),
  fracionado             VARCHAR2(1),
  cst_ipi                VARCHAR2(2),
  cod_enq                VARCHAR2(3),
  largura                NUMBER(10,2),
  altura                 NUMBER(10,2),
  ticket_vinculado       NUMBER(3),
  categoria_fiscal       VARCHAR2(2),
  controlado             VARCHAR2(1),
  descritivoqrcode       VARCHAR2(100),
  mix_base               VARCHAR2(1),
  profundidade           NUMBER(10,2),
  cod_servico_lst        NUMBER(9),
  armazenagem_elevador   VARCHAR2(1),
  tipo_classificacao     NUMBER(9),
  controlaestoque        VARCHAR2(1) default 'T',
  removido_sortimento    VARCHAR2(1),
  descricao_kgl          VARCHAR2(100),
  comissao               NUMBER(10,2),
  validade_congelado     NUMBER(5),
  tp_validade_congelado  NUMBER(1),
  tara_balanca           NUMBER(9,3)
)
