-- Create table
create table VENDAS
(
  id               INT not null,
  data_hora        DATE not null,
  empresa          INT not null,
  pdv              INT not null,
  nf               INT not null,
  tipo_venda       INT,
  operador         INT not null,
  valor            REAL not null,
  data_hora_inicio DATE not null,
  cnpj_cpf         VARCHAR(14),
  fator            REAL,
  lancamento       REAL,
  data_proc        DATE,
  documento        INT,
  ecf              INT,
  cancelado        CHAR(1),
  id_cliente       INT,
  modelo           VARCHAR(2),
  chave            VARCHAR(44),
  cpf_nfp          VARCHAR(14),
  protocolo        VARCHAR(15),
  entrega          VARCHAR(1),
  vl_frete         REAL,
  vl_outras_desp   REAL,
  caixas_entrega   VARCHAR(100),
  nr_sat           INT,
  devolucao        VARCHAR(1) default 'F',
  id_coi           INT,
  nao_estornar     VARCHAR(1)
)

-- Create table
create table VENDAS_DIARIAS
(
  produto                   INT not null,
  empresa                   INT not null,
  data                      DATE not null,
  qtde                      REAL not null,
  valor                     REAL not null,
  custo                     REAL,
  margem_lucro              REAL,
  pmz                       REAL,
  impostos                  REAL,
  sugestao                  REAL,
  devolucao                 CHAR(1) not null,
  datahora                  DATE,
  tipovenda                 INT not null,
  customedio                REAL,
  valor_acrescimos_venda    REAL,
  valor_descontos_venda     REAL,
  valor_acordos_venda       REAL,
  valor_icms_venda          REAL,
  valor_pis_venda           REAL,
  valor_cofins_venda        REAL,
  valor_despesas_venda      REAL,
  valor_comissao_venda      REAL,
  data_proc                 DATE,
  valor_embalagem           REAL,
  valor_impostos_debitaveis REAL,
  valor_margem_lucro        REAL,
  id_area_vendas            INT,
  qtde_promocao             REAL,
  valor_acordos_pack        REAL,
  vl_icms_st_a              REAL,
  vl_ipi_a                  REAL,
  em_oferta                 VARCHAR(1),
  qtde_cancelamento         REAL
)

-- Create table
create table ITENS_VENDA
(
  venda                     INT not null,
  produto                   INT not null,
  qtde                      REAL not null,
  valor                     REAL not null,
  desconto                  REAL not null,
  vendedor                  INT,
  id                        INT not null,
  custoicms                 REAL,
  custosicms                REAL,
  vendatab                  REAL,
  cst                       VARCHAR(3),
  aliquota                  REAL,
  desp_op                   REAL,
  pis                       REAL,
  cofins                    REAL,
  cst_pis                   VARCHAR(2),
  valor_pis                 REAL,
  cst_cofins                VARCHAR(2),
  valor_cofins              REAL,
  custo_medio               REAL,
  custo_liquido_medio       REAL,
  acrescimo                 REAL,
  qtde_promocao             REAL,
  cod_promocao              INT,
  valor_promocao            REAL,
  tipo_venda                INT,
  valor_acordos_venda       REAL,
  valor_icms_venda          REAL,
  valor_despesas_venda      REAL,
  valor_comissao_venda      REAL,
  fator                     REAL,
  valor_embalagem           REAL,
  valor_impostos_debitaveis REAL,
  valor_margem_lucro        REAL,
  id_area_vendas            INT,
  vl_icms_st_a              REAL,
  vl_ipi_a                  REAL,
  em_oferta                 VARCHAR(1),
  ean                       VARCHAR(16),
  codigo_benef_fiscal       INT,
  pontos                    REAL,
  aliq_fcp                  REAL,
  valor_aliq_fcp            REAL,
  cfop                      INT,
  desc_motivo_desconto      VARCHAR(100),
  liberador_desconto        INT
)

-- Create table
create table PRODUTOS
(
  id                     INT not null,
  descritivo             VARCHAR(128) not null,
  datahora_cadastro      DATE,
  datahora_alteracao     DATE,
  descritivo_pdv         VARCHAR(30) not null,
  depto                  INT not null,
  secao                  INT not null,
  grupo                  INT not null,
  subgrupo               INT not null,
  familia                INT,
  nutricional            INT,
  associado              INT,
  unidade_compra         CHAR(2) not null,
  unidade_venda          CHAR(2) not null,
  status                 INT not null,
  composto               INT not null,
  validade               INT,
  tp_validade            INT,
  receita                VARCHAR(4000),
  classificacao_fiscal   VARCHAR(10),
  ipi_tipo               CHAR(1) not null,
  ipi                    REAL not null,
  qtde_embalagems        REAL not null,
  qtde_embalageme        REAL not null,
  piscofins              CHAR(1) not null,
  ipv                    INT not null,
  pesquisa               CHAR(1) not null,
  aceitapdvm             CHAR(1) not null,
  aceitapdve             CHAR(1) not null,
  diasestoque            INT default 0 not null,
  pesol                  REAL not null,
  pesob                  REAL not null,
  similar                INT,
  sazonal                INT,
  cestoque               CHAR(1) not null,
  del_depto              INT,
  del_secao              INT,
  cor                    VARCHAR(20),
  pantone                VARCHAR(20),
  mprima                 INT,
  descritivodel          VARCHAR(100),
  pontos_fidelidade      REAL default 0 not null,
  base_fidelidade        CHAR(1),
  somentecd              CHAR(1) default 'F' not null,
  despesa                REAL not null,
  monofasico             VARCHAR(1) default 'I' not null,
  emite_etiqueta_pedidov CHAR(1) default 'F' not null,
  id_marca_produto       INT,
  utiliza_serie          VARCHAR(1) default 'F' not null,
  origem                 INT,
  excecao_icms           VARCHAR(2),
  lote_venda             INT default 0 not null,
  acrescimo_fracionado   REAL default 0 not null,
  desconto_maximo        REAL default 0 not null,
  aceita_troca           VARCHAR(1) default 'F' not null,
  margem_contribuicao    REAL default 0 not null,
  licenca                INT,
  destinado_maiores      CHAR(1) default 'F' not null,
  alto_risco             CHAR(1) default 'F' not null,
  modo_preparo           VARCHAR(3000),
  excecao_ipi            VARCHAR(3),
  unidade_kgl            CHAR(2),
  qtde_kgl               REAL default 0 not null,
  cest                   VARCHAR(7),
  conservacao            VARCHAR(1000),
  antecipacao_arroz      REAL,
  beneficio_isencao      CHAR(1) default 'F',
  utiliza_aliq_interna   CHAR(1) default 'F',
  lastro                 INT,
  camada                 INT,
  peso_medio             REAL,
  min_dias_validade      INT,
  participa_cotacao      CHAR(1),
  fracionado             VARCHAR(1),
  cst_ipi                VARCHAR(2),
  cod_enq                VARCHAR(3),
  largura                REAL,
  altura                 REAL,
  ticket_vinculado       INT,
  categoria_fiscal       VARCHAR(2),
  controlado             VARCHAR(1),
  descritivoqrcode       VARCHAR(100),
  mix_base               VARCHAR(1),
  profundidade           REAL,
  cod_servico_lst        INT,
  armazenagem_elevador   VARCHAR(1),
  tipo_classificacao     INT,
  controlaestoque        VARCHAR(1) default 'T',
  removido_sortimento    VARCHAR(1),
  descricao_kgl          VARCHAR(100),
  comissao               REAL,
  validade_congelado     INT,
  tp_validade_congelado  INT,
  tara_balanca           REAL
)
